// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/17/2026, 12:01:04 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/salman/remakojayaabadi/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/salman/remakojayaabadi/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/salman/remakojayaabadi/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/salman/remakojayaabadi/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/salman/remakojayaabadi/frontend/plugins/**/*.{js,ts,mjs}","/Users/salman/remakojayaabadi/frontend/composables/**/*.{js,ts,mjs}","/Users/salman/remakojayaabadi/frontend/utils/**/*.{js,ts,mjs}","/Users/salman/remakojayaabadi/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/salman/remakojayaabadi/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/salman/remakojayaabadi/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/salman/remakojayaabadi/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;